### ISSUE TITLE
`nilearn` behaviour with PSC changed

### ISSUE THREAD

**Issue by htwangtw** [SIMEXP/load_confounds#105]
Found when handling PR #96 
Nilearn version 0.7.0
This issue doesn't concert the main package, but should be noted for our related test `test_nilearn_standardize_psc`. The PSC strategy caused confounds not being regressed out in the data when confound variable has mean of 0 or less. Warning message:
```
nilearn/signal.py:81: UserWarning: psc standardization strategy is meaningless for features that have a mean of 0 or less. These time series are set to 0.
```
This issue will be reported to nilearn, and we should expect future changes to this test.

**Comment by pbellec** [comment]
thanks for pointing this out! 

@all-contributors add @htwangtw for bug

**Comment by htwangtw** [comment]
My PR that allow negative mean signal has now been merged to nilearn master branch. It will be in the next bug fix release of 0.7. Will continue to watch this spot and fix up the test!

**Comment by pbellec** [comment]
awesome! thanks for the update!

**Comment by pbellec** [comment]
It's now fixed, thanks again @htwangtw
