### ISSUE TITLE
require nifti file as input and validate extension.

### ISSUE THREAD

**Issue by pbellec** [SIMEXP/load_confounds#129]
This makes the API a bit less flexible, but it would enable to validate that users are using the correct file for their strategy. This is important for the ICA based denoising strategies.

**Comment by htwangtw** [comment]
I worked on this a bit and realise it is likely to conflict with PR #136. I can submit the PR and resolve the merge conflict later?

Although nilearn don't have brilliant cifti and gifti supports yet, I would like to add them as I am using ciftis from fMRIprep myself. 
cifti is simple but gifti would be a bit weird - func.gii comes in pairs (left and right hemispheres). 
We can ignore gifti for now. What do you think?

**Comment by pbellec** [comment]
@htwangtw Thanks for offering to help on this, very much appreciated!

Re PR #136 you are right. There are a few issues on this PR that I will try to fix today. I would also like to get external feedback from at least one other person before merging. If you or @FrancoisPgm could let me know what you think, that would be very much appreciated. 

Re cifti/gifti that would be wonderful. It's definitely of interest for me to be able to start working with surface data. I think it would be easy enough to pass a list of list as input files to support gifti - we will just need a test to check whether re the user specified two nifti files or a single gifti pair. I suggest you open a separate issue for this but absolutely interested in adding this feature for the beta.

**Comment by pbellec** [comment]
Thanks for opening an issue on the cifti/gifti 

PR #136 is now merged (thanks for your contributions). So if you want to work on the `nii` validation, the code base should be ready to go.
