### ISSUE TITLE
generate `sample_mask` 

### ISSUE THREAD

**Issue by pbellec** [SIMEXP/load_confounds#132]
both scrubbing and removal of initial time points can lead to remove time samples entirely. 

It would be useful to generate (and document) usage of a `sample_mask_` attribute in the confound object after loading. 
This mechanism is actually necessary to implement correctly the `scrubbing` strategy of Ciric et al. 2017. 

A related issue should be reported in nilearn: the `sample_mask` option is featured at the initialization of a masker, while there is no reason for the time points removal (or even time points #) to be fixed in the life cycle of a masker object. The `sample_mask` argument should rather be passed to the `*transform*` methods, just like `confounds` is.

**Comment by htwangtw** [comment]
There are some overlapping elements of three of the remaining issues before the beta release, I will address some related issues with the following plan:
1. refactor current code base non-steady-state regressors (in fMRIprep confound output) and modify motion scrubbing method generated regressors to `sample_mask_` (issue #132 and #26)
2. Get new test data with `rmsd` and `non_steady_state_outlierXX` (issue #127 and #26)
3. Write the despiking regressor method; possibly reuse some element of the existing scrubbing method (issue #127)
Step one will need the most inputs and discussions. Let me know what you think.

**Comment by htwangtw** [comment]
I thought I finished working on this but realise we need to double-check if ICA-AROMA nifti has non-steady-state volumes trimmed or not. ICA-AROMA and compcor based methods all trimmed out non-steady-state volumes when calculating the metrics. Needs to check on the new test data I am processing.

**Comment by pbellec** [comment]
re behavior of ICA-AROMA and compcor: good catch. 
It would indeed be important to incorporate an example of that in the example.
So many moving parts in this project!!

Re scrubbing and despiking, indeed in Ciric 2017 scrubbing is implemented through removing time points while despiking is done by adding one-hot regressors. But I think this is a bit arbitrary: nothing prevents to implement scrubbing with one-hot regressors.
I am now thinking it may make more sense to have two separate loading methods `load` and `load_mask`, depending on whether or not the user plans on using `sample_mask`.  See my comments on this PR: https://github.com/SIMEXP/load_confounds/pull/142 I don't have a strong opinion at this stage, I am just trying to find a way for users to understand what to do with the mask, and forcing an explicit API call may help. Please let me know what you think.
