### ISSUE TITLE
compatibility issue with older tsv confound files.

### ISSUE THREAD

**Issue by Yvonneser** [SIMEXP/load_confounds#145]
Hi, I am, trying to implement your code using older outputs of fmriprep (example file: https://ftp.gwdg.de/pub/misc/MPI-Leipzig_Mind-Brain-Body/derivatives/sub-010005/func/sub-010005_ses-02_task-rest_acq-AP_run-02_confounds.txt), however I am unsure what are the names of confounds and do not have a meta data json file in this online data. Any idea for a workaround?
 Thanks a lot!

**Comment by htwangtw** [comment]
Hello @Yvonneser  - thanks for opening an issue. Do you know the version of fMRIPrep the dataset was preprocessed with? From there we can have a better idea what the confounds are. We might not be able to support versions before a certain point, still will be happy to see what I can help with.

**Comment by pbellec** [comment]
@Yvonneser sorry for being so late to the party. Hopefully this response is still useful.

I agree with @htwangtw, this may be too old.
By looking at the file, there are no headers describing the confounds. 
It is not possible to parse confounds with such a file. 
It looks like the file may have been designed to be directly loaded as a numpy array.

You may want to find some documentation on the content of the file, or possibly re-run the processing with a more recent version of fmriprep.

**Comment by Yvonneser** [comment]
Awesome, thanks!
Yvonne
