### ISSUE TITLE
issues in README

### ISSUE THREAD

**Issue by pbellec** [SIMEXP/load_confounds#146]
Just went over the README, and caught a few issues:
 * the section on flexible denoising seems to be gone. 
 * there is a reference to `Params6` in a section. This section also underscores an issue with confounds normalization in nilearn which is addressed in the most recent release.

**Comment by htwangtw** [comment]
. 
> Just went over the README, and caught a few issues:
> 
>     * the section on flexible denoising seems to be gone.
> 

It looks like the content of flexible denoising is still there, just the header got deleted/renamed in https://github.com/SIMEXP/load_confounds/commit/68b7d509dfd93fe7152cce008a0dae2148340261

Those contents are currently under **Noise components**. I think highlighting flexibility is important to make users understand how they can potentially recreate a good chunk of strategy in the Ciric paper.

>     * there is a reference to `Params6` in a section. This section also underscores an issue with confounds normalization in nilearn which is addressed in the most recent release.

This should be an easy fix.

**Comment by htwangtw** [comment]
this is no longer relevant as we migrate the code to nilearn
