### ISSUE TITLE
move from numpy array of confounds to pandas df

### ISSUE THREAD

**Issue by pbellec** [SIMEXP/load_confounds#147]
my understanding is that nilearn maskers are going to support pandas df.
It is a much cleaner format to output confounds, and would be preferable over the numpy arrays. 
This requires minimal changes, as internally load_confounds manipulate the confound array using pandas already.

**Comment by htwangtw** [comment]
This will also simplify a lot of the code from what I am aware of. Shall we aim to merge #142 first?

**Comment by pbellec** [comment]
yes, I am going to look into #142 later today, then we can deal with the df.
