### ISSUE TITLE
how to check the number of scrubbed volumes?

### ISSUE THREAD

**Issue by GerardYu** [SIMEXP/load_confounds#152]
is it possible to check the number of scrubbed or remaining volumes?

**Comment by htwangtw** [comment]
Yes, for the most up-to-date version on the main branch, you can get the total number of remaining volumes this way:
```python
from load_confounds import Confounds
confounds, sample_masks = Confounds(strategy=['high_pass', 'motion', 'global', 'scrub']).load(file)
print(len(sample_masks)
```

However, I would like to redirect you to the developing version implemented on [nilearn main branch](https://github.com/nilearn/nilearn). 

To use the developing version of nilearn:
```
pip install git+https://github.com/nilearn/nilearn.git
```

Once the developing version is released as a stable version, you can install it the normal way on their documentation.
