### ISSUE TITLE
Saving the img back to nii.gz after load confounds level

### ISSUE THREAD

**Issue by Yvonneser** [SIMEXP/load_confounds#153]
Hey Team, 
I am not sure if opening this issue here can help me in this case. 
I have a problem with reshaping the image after doing the load confound level Using the Minmal() function  to continue our analysis extracting the time series data 
The output error :

"Traceback (most recent call last):
  File "/home/yvonne/PycharmProjects/LoadConfounds/LoadConShaymaa.py", line 29, in <module>
    img = np.reshape(img, testImg.shape)
  File "<__array_function__ internals>", line 5, in reshape
  File "/home/yvonne/PycharmProjects/LoadConfounds/venv/lib/python3.8/site-packages/numpy/core/fromnumeric.py", line 298, in reshape
    return _wrapfunc(a, 'reshape', newshape, order=order)
  File "/home/yvonne/PycharmProjects/LoadConfounds/venv/lib/python3.8/site-packages/numpy/core/fromnumeric.py", line 57, in _wrapfunc
    return bound(*args, **kwds)
ValueError: cannot reshape array of size 107304400 into shape (97,115,65,200)

Process finished with exit code 1"

atattched the code file  also 
![image](https://user-images.githubusercontent.com/75316223/145709369-0cddcb26-532b-4ef9-be68-e42ae4786073.png)

Thank You in Advance
Yvonne

**Comment by manzouri** [comment]
@Yvonneser , Hi could you save the output nii.gz? And how ?

**Comment by Yvonneser** [comment]
Hey @manzouri  yesYes I was able to save the img back to nii.gz successfully:
you can look here https://github.com/Yvonneser/fMRIAnalysis/blob/main/LoadConfounds.py
before i saved the file,  you should transform the imag back to 4d dimenstions, using  masker.inverse_transform() function , 
after the transformation you should use the nib.save() to save the img nii.gz 

I hope my answer clears it up for you.
Yvonne

**Comment by manzouri** [comment]
Thanks  @Yvonneser for the prompt reply , that was very useful.
