### ISSUE TITLE
Can't load any strategy

### ISSUE THREAD

**Issue by psymbio** [SIMEXP/load_confounds#157]
To receate the issue just run the Binder linked in the README (https://mybinder.org/v2/gh/SIMEXP/load_confounds/HEAD?filepath=demo%2Fload_confounds_demo.ipynb), the line:

```python
from load_confounds import Params9
```

Results in an import error.

```bash
ImportError: cannot import name 'Params9' from 'load_confounds' (/srv/conda/envs/notebook/lib/python3.7/site-packages/load_confounds/__init__.py)
```

**Comment by htwangtw** [comment]
The project has been migrated to nilearn. Please read the warning message and direct to nilearn tutorials.
