### ISSUE TITLE
create a contributing.md file

### ISSUE THREAD

**Issue by pbellec** [SIMEXP/load_confounds#17]
we want people to feel welcome proposing changes. The tedana project has a great contributing file 
https://github.com/ME-ICA/tedana/blob/master/CONTRIBUTING.md

Consider adapting it for fmriprep_load_confounds. Simplify a bit maybe though, because this project is pretty small, and nowhere as ambitious as tedana.

**Comment by pbellec** [comment]
btw we also need a code of conduct if we add a CONTRIBUTING.md 
https://github.com/ME-ICA/tedana/blob/master/CODE_OF_CONDUCT.md

**Comment by HanadS** [comment]
please have a look

**Comment by pbellec** [comment]
looks good to me, thanks!
