### ISSUE TITLE
add initial volume suppression to reach steady state

### ISSUE THREAD

**Issue by pbellec** [SIMEXP/load_confounds#26]
this would be implemented just like scrubbing.

See this issue:
https://github.com/courtois-neuromod/cneuromod_docs/issues/23

**Comment by pbellec** [comment]
relevant neurostars thread https://neurostars.org/t/non-steady-state-outlier-xx-not-found-in-confound-files/18380/2

**Comment by htwangtw** [comment]
I had a look at fMRIprep and niworkflows code base - that neurostars thread might be a bit out of date. 
The current implementation seems to be, non-steady-state volumes are detected regardless of the presence of single band reference. If there are non-steady-state volumes, it will be reported. If `--dummy-scans` used, the input overwrites the detected result. Cannot really comment on how siemens Prisma deal with reference volume and how that impact fMRIprep.

See selected relevant parts :
[fMRIprep](https://github.com/nipreps/fmriprep/blob/674124ee80b3e2a8affddf005e910e4ca1c97cc0/fmriprep/workflows/bold/base.py#L315-L323)
[niworkflow](https://github.com/nipreps/niworkflows/blob/8433c47cc71a02b7cf60c53222e1f2c1289abe2d/niworkflows/utils/misc.py#L268-L287)
