### ISSUE TITLE
reorganize folders following nilearn standards

### ISSUE THREAD

**Issue by pbellec** [SIMEXP/load_confounds#31]
update setup.py too

**Comment by HanadS** [comment]
what are the nilearn standards?

**Comment by pbellec** [comment]
data stuff (like example confounds) go in a `data` folder. This is actually something you can declare to pip, along with data types. 

The tests go under `tests` 

This issue is addressed through https://github.com/SIMEXP/load_confounds/pull/39

**Comment by pbellec** [comment]
new test suite addressed that issue.
