### ISSUE TITLE
add support for ICA-AROMA

### ISSUE THREAD

**Issue by pbellec** [SIMEXP/load_confounds#52]

**Comment by pbellec** [comment]
very relevant thread: https://neurostars.org/t/getting-started-using-fmripreps-ica-aroma-outputs/16541

and relevant snippet: https://github.com/sjburwell/fmriprep_denoising/blob/master/denoise_fmriprep_output.py#L290-L321

**Comment by htwangtw** [comment]
Question about test data related to #41  - 
I am happy to write the basic method with any fMRIprep LTS version's output, but would prefer to be consistent for the data I use. Is the current test data part of the [nileanr MAIN test data](https://osf.io/5hju4/files/)?
If so I can grap the first subject in the original dataset on [open neuro](https://openneuro.org/datasets/ds000228/versions/1.0.0) and run it on frmiprep `20.2.1` to get started.

**Comment by pbellec** [comment]
yes I think it was this dataset. I'll ping Elizabeth Dupre and Jake Vogel to make sure.

**Comment by pbellec** [comment]
Fixed with the merge of PR #96 Thanks @htwangtw !
