### ISSUE TITLE
add support for scrubbing.

### ISSUE THREAD

**Issue by pbellec** [SIMEXP/load_confounds#53]

**Comment by smeisler** [comment]
I can take a look at this. I know fMRIPrep uses both FD and DVARS to annotate motion outliers, but it seems like most scrubbing approaches only use FD. So I envision scrubbing to involve
1) set a FD threshold (e.g. 0.2 or 0.5 mm based on some literature)
2) set a num outliers threshold (e.g. 4 minutes of remaining data, or 20% data remaining)
3) toggle between basic scrubbing (remove outliers) and "optimized scubbing" (iterative process that involves basic scubbing and then removing continuous data segments that are too short)
4) Return both the one-hot encoded motion outlier confounds and a binary variable for if subject passed motion outlier threshold (step 2)

**Comment by pbellec** [comment]
fixed!
