### ISSUE TITLE
Heads up for potential name changes

### ISSUE THREAD

**Issue by effigies** [SIMEXP/load_confounds#57]
We're going to be going through and conforming fMRIPrep derivatives to the derivatives spec soon, so it's possible that derivatives may change. It might be useful to have some functionality to switch strategies based on fMRIPrep version, if that doesn't alrleady exist.

**Comment by pbellec** [comment]
Thanks for the heads up! This would indeed be important to support multiple fMRIprep versions. We could generate tiny test data with the different versions.

**Comment by pbellec** [comment]
`load_confounds` now supports both naming conventions (for backwards compatibility), thanks to this PR https://github.com/SIMEXP/load_confounds/pull/73 

Closing this issue :clap:

**Comment by pbellec** [comment]
@all-contributors please add @effigies for ideas
