### ISSUE TITLE
some nilearn functions expect  "a pandas Dataframe or string or list of pandas DataFrames"

### ISSUE THREAD

**Issue by HanadS** [SIMEXP/load_confounds#63]
https://nistats.github.io/modules/generated/nistats.first_level_model.FirstLevelModel.html

**Comment by pbellec** [comment]
so.... I don't have the link to the thread handy, but there is debate in the nilearn team about how to harmonize the input of csv in nilearn. I hope they will simply support both csv, numpy arrays and pandas dataframe. In this case, we should switch back load_confounds to output a pandas dataframe, as this is the most sensical structure in our case. But I would wait for those changes to be implemented in nilearn first.

**Comment by HanadS** [comment]
sounds good
