### ISSUE TITLE
confounds in fmriprep-20.2lts release

### ISSUE THREAD

**Issue by srastegarnia** [SIMEXP/load_confounds#72]
In the HCP_trt, **fmriprep-20.2lts** release for confounds, there are just `*-confounds_timeseries.tsv` while Params is looking for  `*confounds_regressor.tsv files`. I'm wondering if load confounds scripts will be modified to can be useable for both versions?

**Comment by pbellec** [comment]
fixed in release 0.6.5

**Comment by pbellec** [comment]
@all-contributors please add @srastegarnia for bug
