### ISSUE TITLE
anatCompCor compartment selection

### ISSUE THREAD

**Issue by smeisler** [SIMEXP/load_confounds#78]
Hi,

Think this is a really valuable project, thanks for putting it together! However, when loading the acompcor components, there should be a way to select either those from the individual WM and CSF masks, or the combined WM+CSF mask. Using both of them would doubly regress signal, which may introduce noise. I did not see this addressed in the parser script. In the confounds.json file there is a "Mask" field associated with each component which denotes the compartment. If you'd want me to try implementing this myself (I have already in a custom script, but would have to adapt it for this), let me know!

Best,
Steven

**Comment by pbellec** [comment]
Hi Steven,

Sorry for the delay. 
Thanks for bringing that up, you are 100% right, this needs to be added. 

I am not sure when I will have time to work on this. 
If you can open a PR I will look at it quickly though.
Even if it's incomplete, we can iterate together. 
I have added some pointers on where to begin.

I guess the compcor mask argument should be added in the following method, something like `mask_compcor` (with a default to WM+CSF?)
https://github.com/SIMEXP/load_confounds/blob/master/load_confounds/parser.py#L94-L108

It will be necessary to add a new helper function to load the confounds.json file in `parser.py`

It can wait, but it will be necessary to update the test data to add the json and incorporate the json file in the tests
https://github.com/SIMEXP/load_confounds/blob/master/load_confounds/data/test_desc-confounds_regressors.tsv
I wanted to re-generate a new test file anyway using the LTS release and all of fimriprep's options (inc AROMA), see issue #41. 

Finally, the new `mask_compcor` argument will need to be added in the `AnatCompCor` strategy 
https://github.com/SIMEXP/load_confounds/blob/master/load_confounds/strategies.py#L205-L236
and `TempCompCor` strategy:
https://github.com/SIMEXP/load_confounds/blob/master/load_confounds/strategies.py#L205-L236

We'll need to add tests to cover the different types of masks (and find sensible conditions to check that the right subset of covariates is pulled):
https://github.com/SIMEXP/load_confounds/blob/master/load_confounds/strategies.py#L205-L236

I think that covers it :)

**Comment by pbellec** [comment]
@all-contributors please add @smeisler for bug

**Comment by smeisler** [comment]
Thanks for the add! This somehow slipped my mind

**Comment by pbellec** [comment]
btw we're working on fmriprep denoising as a  brainhack MTL [project](https://brainhack.org/global2020/project/project_126)

You can join the fun in channel ~fmriprep_denoising on [brainhack mattermost](https://mattermost.brainhack.org)

**Comment by smeisler** [comment]
In addition, we should allow compcor components to be unspecified and load all compcor components for the given modality. fMRIPrep will by default only save out the component set that explains 50% variance, which is a popular alternative to using only the top 10 components.

**Comment by smeisler** [comment]
https://github.com/nipreps/fmriprep/issues/2384 looks like they may include information in the tsv file about what regressors comes from which compartment, which would make it unnecessary to load the json files.

**Comment by pbellec** [comment]
sorry for the delay in response. I am closing this issue with the merge of PR #115 
Again huge thanks @smeisler your contribution to the project is highly appreciated!! 

I have created a separate issue to discuss the defaults for the number of components: https://www.biorxiv.org/content/10.1101/2020.06.21.163964v1 

I have also created a separate thread to monitor a change of behavior in fmriprep for compcor components https://github.com/nipreps/fmriprep/issues/2384
