### ISSUE TITLE
set up all_contributors bot

### ISSUE THREAD

**Issue by pbellec** [SIMEXP/load_confounds#81]
https://allcontributors.org/docs/en/bot/overview

**Comment by htwangtw** [comment]
Someone with admin access needs to add the bot to the repo. After that is really simple!

**Comment by pbellec** [comment]
thanks for the tip, I'll have a look.

**Comment by pbellec** [comment]
thanks @FrancoisPgm for installing the bots. For reference the contribution table is here: https://allcontributors.org/docs/en/emoji-key

**Comment by pbellec** [comment]
@all-contributors please add @FrancoisPgm  for infrastructure and code.

**Comment by pbellec** [comment]
Allright,I think I've added all the contributors. I love @ all-contributors :)
