### ISSUE TITLE
identify an example dataset on openneuro

### ISSUE THREAD

**Issue by pbellec** [SIMEXP/load_confounds#82]
it would need to be preprocessed with the fmriprep LTS and have a complete list of confounds. 

This data will be used both to illustrate the impact of denoising and as test data in `load_confounds`.

**Comment by pbellec** [comment]
maybe having an updated version of this dataset with fmriprep LTS would make sense https://nilearn.github.io/modules/generated/nilearn.datasets.fetch_development_fmri.html

**Comment by pbellec** [comment]
@haoting here is the response from @emdupre regarding the preprocessing of the rsfmri development dataset.

> 
> The current version was processed with fMRIPrep 1.3.0.post2 and uploaded here [https://osf.io/5hju4/ ]. You can find the fMRIPrep generated methods section there (specifically, here : https://osf.io/wjtyq/ ) which describes the options used. If you want to update it you'd probably want to preprocess and push to a similar public OSF. 
> 
> You'd also want to update the fetcher (https://github.com/nilearn/nilearn/blob/29f64ef77013a8ae63c2458f0e2d75cf4007a062/nilearn/datasets/func.py#L1980-L2061). That should largely be a matter of updating this CSV file: https://github.com/nilearn/nilearn/blob/master/nilearn/datasets/data/development_fmri.csv
> I generated that CSV file using this gist : https://gist.github.com/emdupre/3cb4d564511d495ea6bf89c6a577da74
> 
> The "reduced confounds" are selected internally in the dataset fetcher, here: https://github.com/nilearn/nilearn/blob/29f64ef77013a8ae63c2458f0e2d75cf4007a062/nilearn/datasets/func.py#L2065-L2069 , though note that the fetcher can return all confounds. Those reduced confounds in particular were chosen based on a discussion Franz Liem and I had.
> 

One motivation to update the preprocessing is to make sure we are compatible with the LTS fMRIprep release. Another is to generate a more comprehensive list of confounds. I believe the current preprocessed data is missing ica-aroma outputs (necessary for issue #52), as well as some of the json description of confounds which are necessary to properly handle some of them (such as compcor components - see e.g. issue #78 ). 

Finally Elizabeth suggests for us to implement our own fetcher in `load_confounds` rather than push the updated preprocessed data in nilearn.

**Comment by htwangtw** [comment]
(My user name is @htwangtw :sweat_smile: )
Thanks @pbellec for finding these out!
Elizabeth's suggestion is sensible - updating the nilearn one will create a lot of works related to updating the examples etc. 
If it's only processing one subject to update the file in `load_confounds/data/`, I am happy to process a subject through fMRIPrep. Can do a full dataset too but that will take a few days with some constrain from the cluster I have access to. However, if someone else wants to get on this, I am happy to help related to running fMRIPrep, either on their local machine or on an HPC with singularity :slightly_smiling_face:

**Comment by pbellec** [comment]
noted, sorry for using the wrong handle @htwangtw ! 

For the hackathon, it would make sense to simply have a single subject. 
This would let us work on the demo, the test, and the additional preprocessing strategies.

I'll touch base on mattermost to see who could move forward with that.

**Comment by emdupre** [comment]
I did a quick check through OpenNeuro for datasets that already have processed fMRIPrep derivatives available. Although there are a number (the new [DMCC13benchmark](https://openneuro.org/datasets/ds003452/versions/1.0.1), [BOLD5000](https://openneuro.org/datasets/ds001499/versions/1.3.1), or [NARPS](https://openneuro.org/datasets/ds001734/versions/1.0.5)), I didn't see one that include ICA-AROMA. But if someone has a bit more time to check carefully (with `datalad` !), that could end up being another good resource !

**Comment by pbellec** [comment]
Thanks a lot @emdupre I think in any case there is value in re-using the developmental dataset for future expansion of the demo, so I am going to go ahead and preprocess that. 

I am also now aware that many of the confounds variable are triggered by optional flags, and I think it is very unlikely that I will find a "full" confound file unless I create it on purpose (with non-steady images and despiking regressors in addition to aroma).

**Comment by pbellec** [comment]
@all_contributors please add @emdupre and @htwangtw for ideas

**Comment by pbellec** [comment]
@all-contributors please add @emdupre and @htwangtw for ideas

**Comment by pbellec** [comment]
@all-contributors please add @htwangtw for ideas

**Comment by htwangtw** [comment]
This is a test dataset I got from @effigies. He uses it for fitlins test.
https://datasets.datalad.org/?dir=/labs/poldrack/ds003_fmriprep
It was not processed with the latest fMRIPrep, but it will do the job to address issue #52!

**Comment by pbellec** [comment]
this is great @htwangtw . I still think this dataset is missing a few possible confounds (non-steady state volumes and despiking regressors). I will try and generate a really complete dataset with the LTS, but in the meantime I am happy to hear you have something to work with for #52

**Comment by pbellec** [comment]
ds003 is now the new test data. I will generate a new one with all possible confounds for issue #41, starting from the developmental dataset ds000228
